--- ALL SCHEMA GO HERE

CREATE SCHEMA PUBLIC AUTHORIZATION colab_admin;
CREATE SCHEMA AUDIT AUTHORIZATION colab_admin;
CREATE SCHEMA ADMIN AUTHORIZATION colab_admin;
CREATE SCHEMA Activity_Histroy AUTHORIZATION colab_admin